### PR TITLE
feat: add @chartjes ailoads test

### LINKED ISSUE #1: Add @chartjes ailoads test

### PR DESCRIPTION
**Pull request by rpappalax**
r?  @karlht, @chartjes

Closes #1

### CODE REVIEW

**Comment by karlht** [comment]
Are we sure we want to leave this based on `stackbrew/debian:testing` rather than `ubuntu`, given the trouble we had with the other Dockerfile?

**Comment by rpappalax** [comment]
@karlht  i know that Chris has this working 'as-is' and since we still need to convert it to molotov soon, I'm almost tempted to say leave it this way and put in an issue for using ubuntu instead.  will that work for you?

**Comment by karlht** [comment]
Yeah, that'll work.  Merging, with a note to switch this to `ubuntu` at the first sign of trouble.

**Comment by rpappalax** [comment]
Thank you @karlht I've created Issue #4

**Pull request merged**
